#!/usr/bin/env python3

import numpy as np
import sys, getopt

inputfile = ''
pwrs=''
try:
    opts, args = getopt.getopt(sys.argv[1:],"hi:",["ifile="])
except getopt.GetoptError:
   print('final2yoon -i <inputppfile>')
   sys.exit(2)
for opt, arg in opts:
   if opt == '-h':
      print('final2yoon -i <inputppfile>')
      sys.exit()
   elif opt in ("-i", "--ifile"):
      inputfile = arg
#end for

print('\nInput file is: ', inputfile)


filepath1=inputfile
f1=open(filepath1, "r")

at_params=False
paramstr=''
for line in f1:
    if at_params and ('multipliers' in line or line=='\n'):
        at_params=False
    #end if
    if at_params:
      paramstr+=line  
    #end if
    if 'optimal solution' in line:
        at_params=True            
    #end if
#end for
f1.close()
d1=np.array(paramstr.split(),dtype=float)

f = open('params.in','w')
for di,d in enumerate(d1): 

    dstr=str(d)+' x'+str(di+1)+' \n'
    f.write(dstr)

f.close()
print('\nparams.in written')

print()
